export const NEXOTTO_LOGIN_FAIL = "NEXOTTO_LOGIN_FAIL";
export const NEXOTTO_LOGIN_REQUEST = "NEXOTTO_LOGIN_REQUEST";
export const NEXOTTO_LOGIN_SUCCESS = "NEXOTTO_LOGIN_SUCCESS";

export const NEXOTTO_AUTH_FAIL = "NEXOTTO_AUTH_FAIL";
export const NEXOTTO_AUTH_REQUEST = "NEXOTTO_AUTH_REQUEST";
export const NEXOTTO_AUTH_SUCCESS = "NEXOTTO_AUTH_SUCCESS";
